version: "3.4"

services:
  api:
    build:
      context: ..
      dockerfile: src/RichDomainStore.API/Dockerfile
    ports:
      - "8000:80"
    restart: unless-stopped
    depends_on:
      - sqlserver
      - eventstore.db
    networks:
      - api

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "<YourStrong!Passw0rd>"
      ACCEPT_EULA: "Y"
    volumes:
      - type: volume
        source: sqlserver-volume
        target: /var/opt/mssql
    networks:
      - api
   
  eventstore.db:
    image: eventstore/eventstore:20.10.2-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
    networks:
      - api

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  sqlserver-volume:

networks:
  api: 
